name: Build & Push Docker image

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Choose where you want to push the build'
        required: true
        default: Github
        type: choice
        options:
          - DockerHub
          - GitHub
          - Both
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "Start! ${{ github.event.inputs.publish }} on $(date +'%y%m.%d')"
      - name: Push on GitHub
        if: inputs.publish == 'DockerHub'
        run: echo "Push on Docker Hub"
      - name: Push on Docker Hub
        if: inputs.publish == 'GitHub'
        run: echo "Push on GitHub"
      - name: Push on GitHub and Docker Hub
        if: inputs.publish == 'Both'
        run: echo "Push on Docker Hub & GitHub"
